
volumes:
  grafana_data:
  mimir_data:
  prometheus_data:
  
networks:
  pubel:

services:
  prusa_metrics_handler:
    build: .
    container_name: metrics_handler
    restart: unless-stopped
    command: 
      - "--influx-url=http://otel-collector:8086"
      - "--influx-org=pubeldev"
      - "--influx-bucket=prusa"
      - "--influx-token=null"
    ports:
      - 8514:8514/udp # UDP for metrics - I could tell you a joke about UDP, but you might not get it
    depends_on:
      - otel-collector
    networks:
      - pubel

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      -  --web.enable-otlp-receiver
    volumes:
      - ./docs/config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/:/etc/prometheus/
    networks:
      - pubel

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    container_name: otel-collector
    restart: always
    command: 
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - ./docs/config/otel-collector.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus
    networks:
      - pubel

  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - pubel
    volumes:
      - ./docs/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
