
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_data:

networks:
  prusa:

services:
  prusa_metrics_handler:
    build: .
    container_name: prusa_metrics_handler
    restart: unless-stopped
    command: 
      - "--influx-url=http://influxdb:8086"
      - "--influx-org=pubeldev"
      - "--influx-bucket=prusa"
      - "--influx-token=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g=="
    ports:
      - 10011:10011 # prometheus metrics
      - 8514:8514/udp
    networks:
      - prusa

  influxdb:
    container_name: influxdb
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_ORG: pubeldev
      DOCKER_INFLUXDB_INIT_BUCKET: prusa
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: tester
      DOCKER_INFLUXDB_INIT_PASSWORD: hypersupermegatitanturbopassword
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - prusa
    depends_on:
      - prusa_metrics_handler

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - prusa
    volumes:
      - ./docker-grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
