apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: influx
    type: influxdb
    url: http://influxdb:8086
    isDefault: false
    secureJsonData:
      token: EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    jsonData:
      version: Flux
      organization: pubeldev
      defaultBucket: prusa
