receivers:
  influxdb:
    endpoint: 0.0.0.0:8086

exporters:
  otlphttp:
    metrics_endpoint: "http://prometheus:9090/api/v1/otlp/v1/metrics"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [influxdb]
      processors: [batch]
      exporters: [otlphttp]
