receivers:
  influxdb:
    endpoint: 0.0.0.0:8086

exporters:
  otlphttp:
    endpoint: prometheus:4318 
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [influxdb]
      processors: [batch]
      exporters: [otlphttp, prometheus]